"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { browserSupabase } from "@/lib/supabase";
import { Download, Loader2, LogOut, Plus, RefreshCw, Search, Users } from "lucide-react";

type Admission={id:string;admission_id:string;student_name:string;mobile:string;class_name:string;preferred_batch:string;created_at:string};
type Session=Awaited<ReturnType<ReturnType<typeof browserSupabase>["auth"]["getSession"]>>["data"]["session"];

export function AdminDashboard(){
  const [session,setSession]=useState<Session>(null);const [loading,setLoading]=useState(true);const [items,setItems]=useState<Admission[]>([]);const [query,setQuery]=useState("");const [error,setError]=useState("");
  const supabase=browserSupabase();
  const configured=Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);
  useEffect(()=>{if(!configured){setLoading(false);return}supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[configured,supabase]);
  const load=useCallback(async()=>{if(!session)return;setLoading(true);const r=await fetch("/api/admin/admissions",{headers:{Authorization:`Bearer ${session.access_token}`}});const j=await r.json();setLoading(false);if(!r.ok){setError(j.error||"Access denied");return}setItems(j.admissions)},[session]);
  useEffect(()=>{load()},[load]);
  if(!configured)return <main className="flex min-h-screen items-center bg-cream px-5"><div className="card mx-auto max-w-lg text-center"><h1 className="text-2xl font-black">Supabase setup required</h1><p className="mt-3 text-sm leading-6 text-slate-600">Add the environment variables from <code>.env.example</code>, then restart the development server.</p></div></main>;
  if(loading&&!session)return <div className="flex min-h-screen items-center justify-center"><Loader2 className="animate-spin"/></div>;
  if(!session)return <AdminLogin onError={setError} error={error}/>;
  const filtered=items.filter(x=>`${x.student_name} ${x.mobile} ${x.admission_id}`.toLowerCase().includes(query.toLowerCase()));
  async function exportCsv(){const r=await fetch("/api/admin/export",{headers:{Authorization:`Bearer ${session!.access_token}`}});if(!r.ok){setError("Export failed.");return}const blob=await r.blob();const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="rainbow-admissions.csv";a.click();URL.revokeObjectURL(a.href)}
  return <main className="min-h-screen bg-slate-50"><header className="border-b bg-white"><div className="shell flex min-h-20 items-center justify-between gap-4"><div><p className="font-black">Rainbow Admin</p><p className="text-xs text-slate-500">{session.user.email}</p></div><button className="btn-light min-h-10 px-4 py-2" onClick={()=>supabase.auth.signOut()}><LogOut size={16}/> Logout</button></div></header><div className="shell py-10">
    <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Dashboard</p><h1 className="mt-2 text-3xl font-black">Admissions</h1></div><div className="flex gap-2"><button className="btn-light" onClick={load}><RefreshCw size={17}/> Refresh</button><button className="btn-primary" onClick={exportCsv}><Download size={17}/> Export CSV</button></div></div>
    {error&&<p className="mt-5 rounded-2xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}
    <div className="mt-8 grid gap-4 sm:grid-cols-3"><Stat label="Total students" value={items.length}/><Stat label="New this month" value={items.filter(x=>new Date(x.created_at).getMonth()===new Date().getMonth()).length}/><Stat label="Classes served" value={new Set(items.map(x=>x.class_name)).size}/></div>
    <div className="mt-8 grid gap-8 xl:grid-cols-[1fr_360px]"><section className="card overflow-hidden p-0"><div className="flex items-center gap-3 border-b p-5"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search students…" className="w-full outline-none"/></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="p-4">Student</th><th className="p-4">Class</th><th className="p-4">Mobile</th><th className="p-4">Batch</th><th className="p-4">Admission ID</th></tr></thead><tbody>{filtered.map(x=><tr className="border-t" key={x.id}><td className="p-4 font-bold">{x.student_name}</td><td className="p-4">{x.class_name}</td><td className="p-4">{x.mobile}</td><td className="p-4">{x.preferred_batch}</td><td className="p-4 font-mono text-xs">{x.admission_id}</td></tr>)}</tbody></table>{!filtered.length&&<p className="p-10 text-center text-slate-500">No students found.</p>}</div></section><FeeCreator session={session}/></div>
  </div></main>
}
function Stat({label,value}:{label:string;value:number}){return <div className="card flex items-center gap-4 p-5"><span className="rounded-2xl bg-violet/10 p-3 text-violet"><Users size={20}/></span><div><p className="text-2xl font-black">{value}</p><p className="text-xs text-slate-500">{label}</p></div></div>}
function AdminLogin({onError,error}:{onError:(x:string)=>void;error:string}){
  const [busy,setBusy]=useState(false);async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const data=new FormData(e.currentTarget);const {error}=await browserSupabase().auth.signInWithPassword({email:String(data.get("email")),password:String(data.get("password"))});setBusy(false);if(error)onError(error.message)}
  return <main className="flex min-h-screen items-center bg-cream px-5"><form onSubmit={login} className="card mx-auto w-full max-w-md p-8"><p className="eyebrow">Secure access</p><h1 className="mt-3 text-3xl font-black">Admin login</h1><label className="mt-8 block"><span className="label">Email</span><input className="field" type="email" name="email" required/></label><label className="mt-5 block"><span className="label">Password</span><input className="field" type="password" name="password" required/></label>{error&&<p className="mt-4 text-sm text-red-600">{error}</p>}<button disabled={busy} className="btn-primary mt-7 w-full">{busy?<Loader2 className="animate-spin" size={18}/>:"Login"}</button></form></main>
}
function FeeCreator({session}:{session:NonNullable<Session>}){
  const [message,setMessage]=useState("");async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch("/api/admin/fees",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify(form)});const j=await r.json();setMessage(r.ok?"Fee record created.":j.error||"Could not create fee.");if(r.ok)e.currentTarget.reset()}
  return <aside className="card h-fit"><div className="flex items-center gap-3"><Plus className="text-violet"/><h2 className="text-xl font-black">Add fee record</h2></div><form onSubmit={create} className="mt-6 space-y-4"><input className="field" name="admissionId" placeholder="Admission ID" required/><input className="field" name="month" placeholder="Month (e.g. July 2026)" required/><input className="field" name="amount" type="number" min="1" placeholder="Fee amount" required/><input className="field" name="dueDate" type="date" required/><select className="field" name="status"><option value="pending">Pending</option><option value="paid">Paid</option></select><button className="btn-primary w-full">Create fee</button>{message&&<p className="text-sm text-slate-600">{message}</p>}</form></aside>
}
